server:
  port: 8080

logging:
  level:
    root: INFO

management:
  server:
    port: 8088
  defaults:
    metrics:
      export:
        enabled: false
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
        add-additional-paths: true
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true  # default
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      connect-timeout: 1s  # default
      endpoint: http://localhost:9411/api/v2/spans  # default
      read-timeout: 10s  # default
